openapi: '3.0.2'
info:
  title: Scada Tool API
  version: '1.0'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: https://api.server.test/v1
paths:
  /v1/login:
    post:
      tags: [auth]
      operationId: login
      summary: 登錄拿token
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/LoginDetail'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: 
                type: string
                example: token
        '400':
          description: bad request
        '500':
          description: internal server error
  /v1/scada-data/project:
    post:
      tags: [scada-data]
      operationId: create-project
      summary: 新增scada案場
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateProject'
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '400':
          description: bad request
        '401':
          description: unauthorized
        '500':
          description: internal server error
  /v1/scada-data/{projectId}/upload:
    get:
      tags: [scada-data]
      operationId: upload-scada-data
      summary: 取得上傳scada config檔案的url
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadUrls"
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found
        '500':
          description: internal server error
  /v1/scada-data/{projectId}/config/{version}:
    put:
      tags: [scada-data]
      operationId: upload-scada-data-done
      summary: 上傳檔案完畢，並告知是否deploy
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: version
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/UpdateProjectConfig'
      responses:
        '200':
          description: OK
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found
        '500':
          description: internal server error
  /v1/scada-data/{projectId}:
    get:
      tags: [scada-data]
      operationId: get-scada-data
      summary: 取得對應project的scada config檔案列表
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScadaDataList'
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found
        '500':
          description: internal server error
components: 
  securitySchemes:  
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginDetail:
      type: object
      properties:
        account:
          type: string
        password:
          type: string
    UploadUrls:
      type: object
      properties:
        version:
          type: string
        frontend:
          type: string
        backend:
          type: string
    CreateProject:
      type: object
      properties:
        name:
          type: string
    UpdateProjectConfig:
      type: object
      properties:
        state:
          type: string
          enum: [failed, done, deploy]
    ScadaDataList:
      type: array
      items:
        type: object
        properties:
          version:
            type: string
            description: timestamp
          state:
            type: string
            description: state
