openapi: '3.0.2'
info:
  title: Scada Tool API
  version: '1.0'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: https://api.server.test/v1
paths:
  /v1/login:
    post:
      tags: [auth]
      operationId: login
      summary: 登錄拿token
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/LoginDetail'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: bad request
        '500':
          description: internal server error
  /v1/scada-data:
    post:
      tags: [scada-data]
      operationId: create-project
      summary: 新增scada案場
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateProject'
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '400':
          description: bad request
        '401':
          description: unauthorized
        '500':
          description: internal server error
  /v1/scada-data/{ID}/upload:
    get:
      tags: [scada-data]
      operationId: upload-scada-data
      summary: 取得上傳scada config檔案的url
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadUrls"
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found
        '500':
          description: internal server error
  /v1/scada-data/{ID}/config/{VERSION}:
    post:
      tags: [scada-data]
      operationId: upload-scada-data-done
      summary: 上傳檔案完畢，並告知是否deploy
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
        - in: path
          name: VERSION
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateVersion'
      responses:
        '200':
          description: OK
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found
        '500':
          description: internal server error
  /v1/scada-data/{ID}:
    put:
      tags: [scada-data]
      operationId: upload-scada-deploy-version
      summary: 更新佈署版本(空白不更新)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/UpdateDeployVersion'
      responses:
        '200':
          description: OK
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found
        '500':
          description: internal server error
    get:
      tags: [scada-data]
      operationId: get-scada-data
      summary: 取得scada config檔案列表
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScadaDataList'
        '204':
          description: no content
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found
        '500':
          description: internal server error
components: 
  securitySchemes:  
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginDetail:
      type: object
      properties:
        account:
          type: string
        pwd:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
        state:
          type: string
        platform:
          type: object
          properties:
            name:
              type: string
            roles:
              type: array
              items:
                type: string
    UploadUrls:
      type: object
      properties:
        version:
          type: string
        uploading:
          type: string
    CreateProject:
      type: object
      properties:
        name:
          type: string
    CreateVersion:
      type: object
      properties:
        desc:
          type: string
    UpdateDeployVersion:
      type: object
      properties:
        version:
          type: string
    ScadaDataList:
      type: array
      items:
        type: object
        properties:
          version:
            type: string
            description: timestamp
          is_used:
            type: boolean
          desc:
            type: string   
          create_date:
            type: string
