servers:
- url: http://auth:9080
  description: Auth Service
openapi: 3.1.0
info:
  title: auth
  description: ''
  version: 1.0.0
tags:
  - name: auth
paths:
  /v5/login:
    post:
      summary: 登入取得 uToken
      deprecated: false
      description: ''
      operationId: login
      tags:
        - auth
      parameters:
        - name: X-PLATFORM
          in: header
          description: ''
          required: false
          example: ''
          schema:
            type: string
            enum:
              - scada-tool
              - admin
            x-apidog:
              enumDescriptions:
                scada-tool: scada工具
                admin: 後台管理
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
            example: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudLoginResponse'
              examples:
                '1':
                  summary: Success
                  value:
                    utoken: this is token
                    name: this is username
                    state: good
                    channels:
                      - id: this is admin id
                        name: 管理後台
                        roles:
                          - owner
                      - id: this is app id
                        name: 沐霖行動服務
                        roles:
                          - owner
                          - editor
        '400':
          description: bad request
          content:
            application/json:
              schema: &ref_0
                $ref: '#/components/schemas/ErrorsResponse'
        '401':
          description: unauthorized
          content:
            application/json:
              schema: *ref_0
        '500':
          description: internal server error
          content:
            application/json:
              schema: *ref_0
      security: []
components:
  schemas:
    ErrorsResponse:
      type: object
      required:
        - error
        - status
        - service
      properties:
        error:
          type: string
        service:
          type: string
        status:
          type: integer
          format: int32
    CloudLoginResponse:
      type: object
      required:
        - token
        - name
        - state
        - channels
        - refresh_token
      properties:
        channels:
          type: array
          items:
            type: string
        name:
          type: string
        state:
          type: string
          enum:
            - good
            - changePwd
            - verifyMail
        token:
          type: string
        refresh_token:
          type: string
    Login:
      type: object
      required:
        - account
        - pwd
      properties:
        account:
          type: string
        push:
          type: string
        pwd:
          type: string
  securitySchemes: {}
